### ISSUE TITLE
The installer v4.0 could not work well on windows 7 with python 3.4.2 installed

### ISSUE THREAD

**Issue by tz-arm** [ARMmbed/mbed-cli-windows-installer#12]
Install mbed-cli with all default extras via installer v4.0, there is no shortcut created on desktop.
Could not find python in mbed-cli folder.

**Comment by theotherjimmy** [comment]
@0xc0170 I'm pretty sure that the current innstaller does not have this behavior. Closing; please reopen if I am mistaken.
