### ISSUE TITLE
This repo is private, yet it is linked from the public docs!

### ISSUE THREAD

**Issue by maclobdell** [ARMmbed/mbed-cli-windows-installer#27]
The public documentation at https://os.mbed.com/docs/latest/tutorials/quick-start-offline.html ...

has a link to https://github.com/ARMmbed/mbed-cli-windows-installer/releases, which is private.  

Thus, 99% of customers cannot access it!  

Windows
1. Install Mbed CLI
Download and run the Mbed CLI Windows .exe installer

cc @BlackstoneEngineering  @AnotherButler

**Comment by theotherjimmy** [comment]
This repo is public. Closing.
